### ISSUE TITLE
Class does not exist

### ISSUE THREAD

**Issue by shorif2000** [Sammaye/yii2-audittrail#12]
I have added the requierd line to composer.json. run composer update. In my class i have placed

<code>
 public function behaviors()
    {
    	return [
    		'sammaye\audittrail\LoggableBehaviour'
		    	/*'LoggableBehavior'=> array(
		    			'class' => 'sammaye\audittrail\LoggableBehaviour'//'site.vendor.sammaye.audittrail.LoggableBehavior',
		    	)*/
    	];
    }
</code>

I get the following error

<code>
Class sammaye\audittrail\LoggableBehaviour does not exist
</code>

**Comment by reuhtte** [comment]
And you have sammaye's folder under vendor path? If not, you need to run "composer update" command  in terminal under your project location.

**Comment by Sammaye** [comment]
You may need to run `composer require sammaye/yii2-audittrail` since update won't do it in latter version of composer for some reason

**Comment by krismckay** [comment]
The problem is a typo in the spelling of "LoggableBehviour" .. The package uses "LoggableBehavior" (US spelling) where as the documentation uses "LoggableBehaviour" (ENG/CND spelling)..

**Comment by Sammaye** [comment]
Ah yeah, sorry that has been fixed to comply with US spelling now, thanks
