### ISSUE TITLE
add tag for dependency fix

### ISSUE THREAD

**Issue by schmunk42** [Sammaye/yii2-audittrail#13]
This commit is only available on dev-master: https://github.com/Sammaye/yii2-audittrail/commit/a6a691954e8a30d9a7971d7bf656cb3119b8c8f0

But there should be also a 0.2.0 tag with this commit.

**Comment by Sammaye** [comment]
Done: https://github.com/Sammaye/yii2-audittrail/releases/tag/0.2.0 thanks
