### ISSUE TITLE
Add a defaultFQN setting option to allow for someone to set a global FQN prefix

### ISSUE THREAD

**Issue by jacksumit** [Sammaye/yii2-audittrail#16]
Currently this behavior is storing fully qualified name of the model (for example app\models\Assignment). How can we make it to store non qualified model name Storing just Assignment instead of app\models\Assignment.

**Comment by Sammaye** [comment]
Problem is that if I make a default alias to an FQN then it will normally only fit to one situation. For example, most of the time I used the two tiered app which means that my models directory is: `common\models`.

So the FQN (this is why Yii requires FQN all the time too) solves this problem.

**Comment by jacksumit** [comment]
Problem with storing FQN of models in table is that you have to provide long keys in query. For example select * from tbl_audit_trail where model ='app/models/Assignment' and modem_id=167.

How about having a parameter like table name. audittrail.storeFQN=true|false?

**Comment by Sammaye** [comment]
It is possible though it is good to note that if you have an index on that field the overhead should be almost negligible to just having the field value of "Assignment".

Even with the config it would still be a problem here: https://github.com/Sammaye/yii2-audittrail/blob/master/AuditTrail.php#L106 whereby you can get the audited model.

So it would need actually a `defaultFQN` config and if that is set it will do stuff

**Comment by jacksumit** [comment]
Thanks Sammaye. I got your point.

One more question. Why are we setting _oldAttributes in behaviour class when Yii automatically maintains _oldattributes. 

Btwn thanks for your work on this plugin. I have been using it since yii 1.1

**Comment by Sammaye** [comment]
I cannot quite remember, I did use Yii2's own `_oldAttributes` but there was something about it that I had to revert back to using a custom tracker.

I can't remember why and it might not even be true any more since this plugin was first made on Yii2 beta.

**Comment by Sammaye** [comment]
That commit above should do it
