### ISSUE TITLE
How can we fetch value of a audit trailed attribute on a given date

### ISSUE THREAD

**Issue by jacksumit** [Sammaye/yii2-audittrail#17]
How can we get the value of an audit trailed attribute on particular date? For example say there is a attribute Status in a model which undergone below changes

01/01/2015 - Open
05/02/2015 - In Progress
07/04/2015 - Waiting
04/07/2015 - Closed

Similary status on other records also got changed on different dates.

Now say I want to generate a report of all the records of this model with status as on 01/04/2015. How can I achieve that? 

I propose to add another column in audit trail which stores the end time stamp of that audit trail record (say endTimeStamp). So on any update we have to first search if any previous audit trail record exists for same attribute and same model and model id. If yes we have to stamp the endTimeStamp with the time stamp of new audit trail record. Now we can identify the value of status attribute of model on any date by checking timestamp <= '01/04/2015' and (endTimeStamp > '01/04/2015' or endTimeStamp is null).

**Comment by Sammaye** [comment]
I am having trouble visualising how you want endTimestamp to actually work. Can you explain a bit more, maybe add some pseudo code to explain how the endTimestamp will be maintained?

I mean personally I would query for the dates of your choice, by the field of your choice (status here I presume) by the values you want (all it seems).

That's how I would solve this in my current view.

**Comment by jacksumit** [comment]
I am looking for something like below in leavetrail method:

$previousLog=  AuditTrail::find()
                    ->where(['model'=>$log->model, 'model_id'=>$log->model_id,'field'=>$log->field])
                    ->orderBy('stamp desc')
                    ->limit(1)
                    ->one();
            if($previousLog)
            {
                $previousLog->endStamp=$log->stamp;
                $previousLog->save();
            }
            return $log->save();

Say I am audit trailing COMPANY status then this will allow me to write below query to find out the status of companies on a past date even if no audit trail record is created on that day.

SELECT company.*, tbl_audit_trail.new_value 
FROM company t1
LEFT OUTER JOIN tbl_audit_tail t2 on t2.model_id=t1.id and t2.model='app\\models\\Company' and t2.field='status' and t2.stamp <= '2015-10-01'  and t2.endStamp > '2015-10-01'

**Comment by Sammaye** [comment]
This sounds like something better done in your active record if I understand correctly.

This (I still am not totally understanding) seems like an extra huge edge case (I don't know enough about the scenario where this is being implemented and doing so would bring this thread off topic) and since I would probably have to add what you got there into the audit trail anyway it seems probably better that it is done on your end only adding that code to your active record after save (most likely).

Updates should not break your functionality. If you customise the migration script to add your new field it should be fine.

Either way I don't think this would be a particularly valuable addition to the core. I am still a bit concerned about the entire scenario. I probably would have found another way of doing this, it sounds odd.

**Comment by Sammaye** [comment]
I thin your code is also wrong up there, shouldn't you be updating all previous audit records (maybe thousands on complicated, high traffic, records) with the endstamp, I have a production scenario where this simply would not be feasible?

**Comment by Sammaye** [comment]
Also you don't take into account records that can fall into gaps by no edit to them I think.

Either way this sounds like a very dodgy addition

**Comment by jacksumit** [comment]
No problem.. Thanks for considering. I will find some alternate way to do it. 

No there will always be only one record which will not have endStamp because every new record in audit trail is updating the previous audit trail record.

Even for no edit records at-least there will be a record with action SET. endStamp will be null for this case because no updated are done. This can be taken care by adding or condition as below.

SELECT company.*, tbl_audit_trail.new_value 
FROM company t1
LEFT OUTER JOIN tbl_audit_tail t2 on t2.model_id=t1.id and t2.model='app\models\Company' and t2.field='status' and t2.stamp <= '2015-10-01' and (t2.endStamp > '2015-10-01'  or t2.endStamp is null)

Anyway I will implement it outside the plugin. That's fine. This solution is required whenever there is a requirement to fetch previous value of a field on some random date.

**Comment by Sammaye** [comment]
Let me think about this some more, maybe you can add more of the scenario, like what you intend to achieve in terms of (I assume) displaying this, or what the data is for? Atm I have seen the intended implementation but it that only shows a small fraction, I am probably missing something and I am sure it is crucial to understanding your reasoning for this.

**Comment by jacksumit** [comment]
Take an example of lead management system (LMS) of an education institute. Each candidate who want to take admission in institute will be created in LMS  as a lead. A lead can progress through various statuses. 1. Created - Default Progress Level
2. Registered - When candidate has registered for entrance exam
3. Test Fee Deposited - When entrance exam test fee deposited
4. Test Booked 
5. Passed/Failed - Candidate has qualified the entrance exam or not.
6. Fee Deposited - Academic fee is deposited

Each lead can belong to one course. Now I want create a dashboard where I can see the number of leads in each progress level for each course. I also want to compare these number to a past date (ex: one week back) to see how much progress has been done since that date. I also want to compare this data against last year to check how good/bad we are tracking to last year. A sample report is attached below.

![image](https://cloud.githubusercontent.com/assets/13305490/10784770/08711828-7db4-11e5-87e6-bec3a9b2767d.png)

Check out the compare to date and number in small in bottom left of the cells. These small numbers displays the change since date selected in compare to date. User can select any date in Compare to date field and these small number should update to display change since that date.

To achieve this we need to know the old value of the field Progress Level on the selected date and for this we can use the query given in my earlier post if endStamp is available in table.

**Comment by Sammaye** [comment]
Ah ok I get this now, the interface makes it make sense.

My concern about non-changes are solved by you querying for null endstamp as well.

Hmm, since we still don't wanna do this for everyone (not everyone will like the idea of covering another query for every audit record) we could add this as a flag to track it.

Would need a good name something that describes it.

**Comment by Sammaye** [comment]
Hmm, also gotta think if someone activates it will it do what they want. If not could it be expanded to do what they want or will it become a white elephant in the code...

**Comment by jacksumit** [comment]
There might be scenarios where we do not want to stamp endStamp for all the fields. Not all audit trailed fields require to be used in reporting example like above. I think it should be configurable at field level if endStamp should be stamped for a field or not.  May be we can add another configuration parameter allowedWithendStamp similar to allowed and ignored. Fields defined in this parameter will be logged with endStamp. All other fields will be audit trailed with endStamp.

**Comment by Sammaye** [comment]
Indeed your only doing it on status, hmmm

**Comment by Sammaye** [comment]
I wonder if I should leave this as too specific to your case for the minute ad wait to see if I get any more requests for this.

Would be okay to you?

**Comment by jacksumit** [comment]
No problem. Thats perfectly fine.

According to you what is the best way to implement it outside the plugin? I need to stamp the endStamp on the previous record with exactly the same value which is being stamped on stamp field in new audit trail record. So doing it in Active Record save record is bit difficult because stamp value of new record will not be available there.

**Comment by Sammaye** [comment]
I would say in after sve do the find of the audit trail and make the endtime of that the save tie of the record, it should be the same if you are working on day resolution.
