### ISSUE TITLE
implement with RBAC

### ISSUE THREAD

**Issue by zainalawaludin** [Sammaye/yii2-audittrail#21]
Hi how to implement this extension on RBAC ? i want log each change like auth_item, auth_assigment, auth_item_child, but i confuse where i put sammaye\audittrail\LoggableBehavior. FYI i use Yii::$app->authManager for CRUD. Thanks

**Comment by Sammaye** [comment]
I don't think this is possible atm due to the models being in core. You would need to extend those classes

**Comment by Sammaye** [comment]
but then those classes are not standard models

**Comment by Sammaye** [comment]
I am going close this since having checked even further I do not think it is possible without doing a fair bit of writing inside of the auth manager itself
