### ISSUE TITLE
Handling related data

### ISSUE THREAD

**Issue by keithslater** [Sammaye/yii2-audittrail#22]
What is the best way to use this plugin when some of the changed fields are related data. Currently the values are the id's of the related fields and when I display them, it of course displays the id's. What would be the best way to store what the related field's data is?

**Comment by Sammaye** [comment]
Currently the best way is to record that related model separately. So an example I do in production atm is to record titles and products, I record both models separately despite being related

**Comment by keithslater** [comment]
Can you show an example of what you mean?

**Comment by Sammaye** [comment]
So you can imagine I have:
```php
class Title extends ActiveRecord
{
    // Behaviour rules go here
}

class Product extends ActiveRecord
{
    // Behaviour
}
```
Now you go to save the parent record:
```php
$title->save();
```
You now also know your related records (you can create a containing transaction for ACID reasons if you want this is just pseudo) to save and save them:
```php
foreach($title->products as $p){
     $p->save();
}
```
Now you have the audit record saved in the DB under model and ID (PK).

**Comment by keithslater** [comment]
I think I might not have explained myself.

Say I have a projects table and a project has a stage. Stage is a related table.

Then say in the project, I update the stage from Lead to Prospect, changing the stage id in the projects table from 1 to 2. Currently it records old_value = 1, new_value = 2. Where I would rather it say old_value = Lead, new_value = Prospect.

**Comment by Sammaye** [comment]
You could rewrite parts of the ext succeed in this but thee better way is to do this as you process the rows. Within the display you would detect  these fields and apply the data transformation to them

**Comment by Sammaye** [comment]
Since this has aged I am going to close this now. Let me know if you need further help from me

**Comment by user1007017** [comment]
Hi, great extension. But how could I get the `old_value` of the related model into the audit_trail table?
```
 public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            foreach($model->ansprechpartners as $p){
                $p->save();
            }

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
```
![image](https://cloud.githubusercontent.com/assets/2892499/26039321/e0a6034e-3919-11e7-81ff-be7bc9570ce0.png)

**Comment by Sammaye** [comment]
Have you added the behaviour to the related model as well?
