### ISSUE TITLE
Migrations do not work on Postgresql

### ISSUE THREAD

**Issue by alxkolm** [Sammaye/yii2-audittrail#24]
Migrations do not work on Postgresql. Migration class  `m161004_132206_change_action_field`

```
*** applying m161004_132206_change_action_field
    > alter column action in table tbl_audit_trail to ENUM('CHANGE', 'CREATE', 'DELETE', 'SET') NOT NULL ...Exception 'yii\db\Exception' with message 'SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "NOT"
LINE 1: ...ion" TYPE ENUM('CHANGE', 'CREATE', 'DELETE', 'SET') NOT NULL
                                                               ^
The SQL being executed was: ALTER TABLE "tbl_audit_trail" ALTER COLUMN "action" TYPE ENUM('CHANGE', 'CREATE', 'DELETE', 'SET') NOT NULL'
```

**Comment by alxkolm** [comment]
I think it is not necessary restrict column by ENUM type, because people want to set custom values in `action`

**Comment by uldisn** [comment]
Using ENUM is small optimization. My suggestion is in migration execute altering to ENUM only, if MySql.

**Comment by alxkolm** [comment]
But whenever I want set custom `action` I need alter column schema. It's very tedious.

**Comment by Sammaye** [comment]
I thought the enum change was a bad idea

**Comment by Sammaye** [comment]
Even for mysql users, this scenario is a common one whereby enum would cause too much application logic in the database. Current thinking is that the database should be dumb to the application rather than have two layers of validation at times, especially with very large tables spanning 30 million+ records, which audit tables can

**Comment by Sammaye** [comment]
I have decided to remove this for the time being https://github.com/Sammaye/yii2-audittrail/commit/8e38c7f2f8b54ec4aa45fb580fc1e65b8036e9d4 I think it is more trouble than it is worth

**Comment by alxkolm** [comment]
Fully agree
