### ISSUE TITLE
Migration is not working

### ISSUE THREAD

**Issue by Sammaye** [Sammaye/yii2-audittrail#6]
http://www.yiiframework.com/extension/yii2-audittrail/#c19055

**Comment by missjewel** [comment]
hi, I install the module in yii2 advanced but, how execute o run it. It have interface?

**Comment by Sammaye** [comment]
You mean the migration?

**Comment by missjewel** [comment]
Yes

**Comment by Sammaye** [comment]
No you run it with the migrate command but since it aint working it won't do anything. I need to fix it but I don't really use SQL anymore as such I need provision time to setup a server

**Comment by Sammaye** [comment]
Ok I have now been able to service a SQL server and have been able to fix this. However, I believe you must copy the migration within the folder to your `console/migrations` folder for it to work since that is the only folder that Yii2 searches, but then it does.

**Comment by Sammaye** [comment]
Fixed readme to explain about migration a bit more and fixed formatting of readme
