### ISSUE TITLE
Copying of migrations folder

### ISSUE THREAD

**Issue by arogachev** [Sammaye/yii2-audittrail#7]
Why it's needed? You can just execute ```migrate``` command with ```--migrationPath``` option.

**Comment by nineinchnick** [comment]
Probably to adjust timestamps in migration names to match your project so you can migrat down properly in order.

**Comment by nineinchnick** [comment]
Oh, somebody just posted an issue about migration order in yiisoft/yii2#7924

**Comment by arogachev** [comment]
What about specifying ```--migrationPath``` with ```migrate/down``` too?

**Comment by nineinchnick** [comment]
You're probably right. Still, that's just a suggestion. Maybe the author wrote that before such param was available in yii2. Let's wait for his opinion.

**Comment by Sammaye** [comment]
If I am honest I didn't actually see that param (I did originally write
this script way before migration commands had any real options or even
worked properly), I was quickly browsing the migration help section
recently to complete the migration after I was told that the latest Yii2
simply did not like my script (was quite busy) and the way I got it working
was to just copy the file to Yii's console folder, I know how Yii in
general does not like slow recursive searching of folders so I just added
that disclaimer.

But now that I think of it the ordering does concern me, other tables
should probably exist before this one, but the audit trail table is quite
free standing so it shouldn't be a horror if t is made first or last.

**Comment by arogachev** [comment]
Yes, tested it on my own extension. ```--migrationPath``` can be also specified with ```migrate/down```.

**Comment by Sammaye** [comment]
Gonna close this, I have added a note about migrationPath to the readme
